double num1, num2, soma = 0;
Console.WriteLine("Olá!");
Console.Write("digite um número: ");
num1 = double.Parse(Console.ReadLine());
Console.Write("Digite outo número: ");
num2 = double.Parse(Console.ReadLine());
soma = num1 + num2;
// Console.WriteLine("soma de {0} + {1} = {2}", num1, num2, soma);
Console.WriteLine("soma de " + num1 + num2 + "é de " + soma);
Console.Read();